name: i386 linux tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.21.4
          cache: false

      - name: Cache Go modules
        id: cache-go-mod
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
    
      - name: Install dependencies
        run: go mod download

      - name: Run tests
        run: go test -short ./...
        env:
          GOOS: linux
          GOARCH: 386
